### ISSUE TITLE
Cannot run main

### ISSUE THREAD

**Issue by vladimirkovacevic** [miloskalicanin/gi_2019_project#1]
>> python main.py -c 1 2 -f test/Coffea\ arabica\,\ Chromosome\ 1c.fa -p ATGCATG
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from Heuristics.good_suffix import GoodSuffix
ImportError: No module named Heuristics.good_suffix

**Comment by miloskalicanin** [comment]
Fixed in e031adad27fb61c1630215dd45eee8b23a5bb7a8.
